collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4960716
  brandStrength: 0.981182
  lightness: 0.8840645
  brandColors:
    - '#BDCFCE'
    - '#382F3A'
    - '#776566'
    - '#C7906E'
    - '#ACDF43'
  rhythmicContrast: 0.06568156
typography_spectrum: 0.4336918
layout_spectrum: 0.827957
name: Blackmarket
